# Generated by Django 4.2.16 on 2024-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_verified_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
