# Generated by Django 4.2.16 on 2024-11-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
