# Generated by Django 4.2.16 on 2024-11-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_reset_password_code_user_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropAveragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, unique=True)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
