# Generated by Django 4.2.16 on 2024-11-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_reset_password_code_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Rather Not Say', 'Rather Not Say')], max_length=20),
        ),
    ]
